'use client';

import React from 'react';
import { useSimulation } from '@/context/SimulationContext';
import { CognitivePipeline } from '@/components/CognitivePipeline';
import { TaskDecomposition } from '@/components/TaskDecomposition';
import { RiskMeter } from '@/components/RiskMeter';
import { DecisionPanel } from '@/components/DecisionPanel';
import { PrivateModelReasoningCard } from '@/components/PrivateModelReasoningCard';
import styles from './cognitive.module.scss';
import { Brain, FileCode, CheckSquare2, Sparkles } from 'lucide-react';

export default function CognitivePage() {
  const { state } = useSimulation();

  return (
    <div className={styles.cognitivePage}>
      <div className={styles.pageHeader}>
        <div className={styles.titleGroup}>
          <h1 className={styles.title}>
            <Brain size={24} color="#a855f7" />
            <span>C-ASA COGNITIVE REASONING ENGINE</span>
          </h1>
          <p className={styles.subtitle}>
            SIMULATED COGNITIVE PROCESS: Problem formulation, dynamic task decomposition, multi-objective risk evaluation, and closed-loop actuation.
          </p>
        </div>

        <div className="badge badge-primary">
          CLOSED-LOOP AUTONOMIC REASONING
        </div>
      </div>

      {/* C-ASA Private Cognitive Reasoning Model Card */}
      <PrivateModelReasoningCard />


      {/* Large 8-Stage Visual Pipeline */}
      <CognitivePipeline />

      {/* Narrative & Context Split Grid */}
      <div className={styles.processNarrativeGrid}>
        {/* Left: Problem & Context Breakdown */}
        <div className={styles.narrativeCard}>
          <div className={styles.cardHeader}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <FileCode size={18} color="#00ffcc" />
              <span>C-ASA RECEIVED EVENT & CONTEXT</span>
            </div>
            <span className="mono-tag" style={{ color: '#00ffcc' }}>INGEST_STAGE</span>
          </div>

          <div className={styles.contentBlock}>
            <div className={styles.blockTitle}>Formulated Problem</div>
            <p>
              Severe anomalous traffic concentration on Router R2 interface eth2 causing buffer depletion, 8.7% packet drop rate, and SLA latency violation exceeding 140ms.
            </p>
          </div>

          <div className={styles.contentBlock}>
            <div className={styles.blockTitle}>Contextual Telemetry Ingestion</div>
            <ul style={{ paddingLeft: '1.2rem', margin: 0 }}>
              <li>High packet volume: 5,920 pkts/sec (380% above baseline)</li>
              <li>High round-trip latency: 146ms (Threshold: 45ms)</li>
              <li>Entropy score: 0.84 indicating distributed volumetric flood</li>
              <li>Critical Server Core gateway at risk of cascading failure</li>
            </ul>
          </div>

          <div className={styles.contentBlock}>
            <div className={styles.blockTitle}>Plan Generated by Cognitive Engine</div>
            <ol style={{ paddingLeft: '1.2rem', margin: 0 }}>
              <li>Request formal diagnostic evidence from Security Agent</li>
              <li>Query Policy Agent for low-latency bypass routes</li>
              <li>Calculate multi-factor risk matrix across alternate routes</li>
              <li>Select safest and SLA-compliant network adaptation</li>
              <li>Execute dynamic OpenFlow flow modification on Router R1</li>
            </ol>
          </div>
        </div>

        {/* Right: Real-time Decision & Risk Assessment */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <RiskMeter />
          <DecisionPanel />
        </div>
      </div>

      {/* Full Task Decomposition Component */}
      <TaskDecomposition />
    </div>
  );
}

