# Generated by Django 4.2.7 on 2026-08-31 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEvent',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('SUCCESS', 'Success')], default='INFO', max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('phase', models.CharField(default='NORMAL', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutonomicAgent',
            fields=[
                ('agent_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(default='MONITORING', max_length=50)),
                ('task', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=95)),
                ('risk_level', models.CharField(default='LOW', max_length=30)),
                ('color', models.CharField(default='#0284c7', max_length=30)),
                ('last_event', models.CharField(blank=True, max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('node_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('server', 'Server'), ('host', 'Host'), ('cloud', 'Cloud Gateway')], default='router', max_length=20)),
                ('ip_address', models.GenericIPAddressField(default='10.0.0.1')),
                ('mac_address', models.CharField(blank=True, max_length=30, null=True)),
                ('port_capacity', models.CharField(default='10.0 Gbps', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('STANDBY', 'Standby'), ('PROTECTED', 'Protected'), ('CRITICAL', 'Critical'), ('BYPASSED', 'Bypassed'), ('DEGRADED', 'Degraded')], default='ONLINE', max_length=30)),
                ('load', models.IntegerField(default=15)),
                ('x_pos', models.IntegerField(default=400)),
                ('y_pos', models.IntegerField(default=250)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('link_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('link_type', models.CharField(choices=[('normal', 'Normal'), ('anomalous', 'Anomalous'), ('bypass', 'Bypass Route'), ('inactive', 'Inactive'), ('standby', 'Standby')], default='normal', max_length=30)),
                ('traffic_level', models.CharField(default='low', max_length=20)),
                ('bandwidth_gbps', models.FloatField(default=10.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='simulation.networkdevice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='simulation.networkdevice')),
            ],
        ),
        migrations.CreateModel(
            name='BRSKIVoucher',
            fields=[
                ('voucher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=50)),
                ('pinned_domain_cert', models.CharField(default='SHA256:7B:3A:9F:88:C1:4E:02:D5:A6', max_length=255)),
                ('domain_registrar', models.CharField(default='casa-autonomic-registrar.domain.net', max_length=150)),
                ('masa_signature', models.TextField(blank=True)),
                ('ldevid_cert', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='VALIDATED_AND_ENROLLED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.networkdevice')),
            ],
        ),
    ]
